import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import useSWR from 'swr'
import styled from 'styled-components'
import {useRouter} from "next/router"

// function to fetch a particular url and return the data as json
const fetcher = url => fetch(url).then(r => r.json())

export default function BookDetail() {
    const router = useRouter() // get access to our router object
    const { title } = router.query // gives us access to the end of URL
    // localhost:3000/Lolita -> title = "Lolita"

  // first param is path of API endpoint (what will be fetched)
  // second param is the fetcher function that should execute to get the data
  const { data, error } = useSWR(`api/books/${title}`, fetcher)
  // if api encounters an error, this will render
  if (error) {
    return <Main>
      Error
    </Main>
  }

  // if data has not been resolved yet
  // this renders
  if(!data) {
    return <Main>
      Loading...
    </Main>
  }

  // if data is rendering
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BookWrapper>
          <BookTitle>{title}</BookTitle>
          <BookAuthor>by {data[0].author}</BookAuthor>
          <h3>Pages: {data[0].pages}</h3>
          <h4>Year: {data[0].year}</h4>
          <a href={data[0].link}>Learn more!</a>
        
          {/* {JSON.stringify(data)} */}
      </BookWrapper>
    </Container>
  )
}

const BookWrapper = styled.article`
    border: 2px solid black;
    border-radius: 5px;
    padding: 10px;
`

const BookTitle = styled.h1`
    color: green;
`

const BookAuthor = styled.h3 `
    color: blue;
`
