import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import useSWR from 'swr'
import styled from 'styled-components'
import AuthorList from '../components/AuthorList'


// function to fetch a particular url and return the data as json
const fetcher = url => fetch(url).then(r => r.json())

export default function Home() {
  // first param is path of API endpoint (what will be fetched)
  // second param is the fetcher function that should execute to get the data
  const { data, error } = useSWR('api/authors', fetcher)

  // if api encounters an error, this will render
  if (error) {
    return <Main>
      Error
    </Main>
  }

  // if data has not been resolved yet
  // this renders
  if(!data) {
    return <Main>
      Loading...
    </Main>
  }

  // if data is rendering
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthorList authors={data}/>
    </Container>
  )
}

const AuthorWrapper = styled.article`
    border: 2px solid black;
    border-radius: 5px;
    padding: 10px;
`